version: '3'
services:
  
  app:
    build: 
      context: .
      dockerfile: django.Dockerfile
      args:
        - DB_HOST=db
        - DB_PORT=$DB_PORT
        - APP_PORT=$APP_PORT
        - MYSQL_DATABASE=$MYSQL_DATABASE
        - MYSQL_USER=$MYSQL_USER
        - MYSQL_PASSWORD=$MYSQL_PASSWORD
        - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
        - MYSQL_ALLOW_ROOT_PASSWORD=$MYSQL_ALLOW_ROOT_PASSWORD
    image: django_web_app:pure_web_app
    container_name: web_app
    volumes:
      - .:/code      
    ports:
      - 8001:8000    
    depends_on:
      - db

  db:
    build: 
      context: .
      dockerfile: mysql.Dockerfile
    image: django_mysql:pure_db
    container_name: db
    env_file:
      - ./.env   
    restart: always   
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - $DB_PORT:3306   
