version: '3'
services:
  
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - DB_HOST=db
        - DB_PORT=$DB_PORT
        - APP_PORT=$APP_PORT
        - MYSQL_DATABASE=$MYSQL_DATABASE
        - MYSQL_USER=$MYSQL_USER
        - MYSQL_PASSWORD=$MYSQL_PASSWORD
        - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    image: app:django
    container_name: web_app
    volumes:
      - .:/code      
    ports:
      - $APP_PORT:8000    
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    env_file:
      - ./.env   
    restart: always   
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - $DB_PORT:3306    

volumes:
  mysql_data:
