name: Docker Image CI

on:
  push:
    branches: [ "main","features/**" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2.1.6
      with:
        path: /tmp/.buildx-cache
        key: ${{runner.os}}-buildx-${{ github.sha}}
        restore-keys: |
          ${{ runner.os }}-buildx
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
#     - name: Start containers
#       run: docker-compose -f "/code/docker-compose.yml" up -d --build
    - name: Login to Quay.io
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
    - name: Login to Quay.io
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
   
#     - name: Build and Push Docker image
#       uses: docker/build-push-action@v2
#       with:
#         context: .
#         file: ./docker-compose.yml
#         push: true
#         tags: quay.io/${{ secrets.QUAY_ORG }}/${{ secrets.QUAY_REPO }}:latest
    
    # - name: Build and push MySQL image
    #   run: |
    #     docker build -f mysql.Dockerfile -t quay.io/${{ secrets.QUAY_ORG }}/pure_db:latest .
    #     docker push quay.io/${{ secrets.QUAY_ORG }}/pure_db:latest
    # - name: Build and push Django image
    #   run: |
    #     docker build -f django.Dockerfile -t quay.io/${{ secrets.QUAY_ORG }}/pure_web_app:latest .
    #     docker push quay.io/${{ secrets.QUAY_ORG }}/pure_web_app:latest
    - name: Build and Push Docker Images
      run: |
        docker-compose build
        docker-compose push
        
#     - name: Build and Push Docker image
#       uses: docker/build-push-action@v2
#       with:
#         context: .
#         file: ./mysql.Dockerfile
#         push: true
#         tags: quay.io/${{ secrets.QUAY_ORG }}/pure_db:latest
        
#     - name: Build and Push Docker image
#       uses: docker/build-push-action@v2
#       with:
#         context: .
#         file: ./django.Dockerfile
#         push: true
#         tags: quay.io/${{ secrets.QUAY_ORG }}/pure_web_app:latest


